### ISSUE TITLE
24.11 Won't work

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ankipalace/Advanced-Card-Styles#12]
When clicking Advanced Editor button it sometimes won't open the ability to edit. Not able to reproduce it every time. 

Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.2-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1625103157/Buttons.py", line 263, in advancedEditorButtonAction
    AdvancedStylerGui.ASGUI(self.clayout)
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1625103157/AdvancedStylerGui.py", line 29, in __init__
    self.loadUI()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1625103157/AdvancedStylerGui.py", line 39, in loadUI
    self.loadSettingsFromCss(text)
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/1625103157/AdvancedStylerGui.py", line 269, in loadSettingsFromCss
    int(str(attributes['font-size'])[:len(attributes['font-size']) - 2]))
ValueError: invalid literal for int() with base 10: '1r'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T07:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T06:10, 'None', '']
Advanced Browser ['874215009', 2024-10-27T10:20, 'None', '']
Advanced Card Styles ['1625103157', 2021-12-28T12:50, 'None', '']
Advanced Copy Fields ['1898445115', 2024-01-08T12:01, 'v0.4.01', '']
AnKing Note Types Easy Customization ['952691989', 2024-10-21T10:29, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T12:26, 'None', '']
AnkiHub ['1322529746', 2024-12-02T15:00, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T11:07, 'None', '']
Audiovisual Feedback ['231569866', 2023-07-08T23:34, '0.8', mod]
Batch Editing ['291119185', 2023-10-25T20:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T11:25, 'None', '']
Bionic Reading ['649714433', 2023-10-26T17:24, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T12:16, 'None', '']
Calculate New Cards To Do ['2014569756', 2022-05-19T01:38, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-30T17:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T04:27, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T20:22, 'v1.0.2', '']
Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T13:15, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T07:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T05:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-11-16T05:23, '6.21', mod]
Editor ProToolBox - Web importer, quick format, & media scraper ['editor_pro_toolbox', 2023-10-22T17:38, 'None', '']
Exam Notifier ['236593452', 2023-01-19T12:12, 'None', '']
Export Single Tag For Sharing ['960563361', 2022-04-10T17:30, 'None', '']
Extended Card Stats During Review ['1008566916', 2024-02-26T14:07, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T11:58, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-12-01T10:29, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Field AutoComplete ['511710206', 2024-07-20T10:07, 'None', '']
Google Translate ['1536291224', 2024-10-21T10:10, 'None', mod]
High Yield Tags ['1918380616', 2023-01-10T14:14, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-21T15:17, 'None', '']
Image Editor ['307397307', 2022-09-08T00:09, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Learning Step and Review Interval Retention ['1949865265', 2024-01-06T12:48, 'None', '']
Mobile Pop-up Dictionary ['1143247763', 2024-05-04T15:26, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T18:49, 'None', '']
More Overview Stats 21 ['738807903', 2024-08-22T05:14, 'None', '']
Motivanki ['663438166', 2022-06-23T11:38, 'None', '']
New Cards Counter ['635082046', 2022-04-20T16:37, 'None', '']
PDF Exporter ['1442112168', 2023-03-20T19:53, 'None', '']
Pokemanki ['633922407', 2021-02-24T16:44, 'None', '']
Postpone cards review ['1152543397', 2023-04-14T22:29, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T07:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T23:15, 'None', '']
Quick Field Navigation ['734297936', 2019-12-29T21:24, 'None', '']
Quick tagging 21 ['304770511', 2020-02-11T01:17, 'None', '']
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T04:33, 'None', '']
ReColor ['688199788', 2024-03-02T20:45, '3.0', mod]
Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T00:40, 'None', '']
Remote Decks Anki collaboration using Google Docs ['911568091', 2021-09-09T13:45, 'None', '']
Reset Ease ['947935257', 2023-11-11T20:22, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Set Card Ease ['1387847178', 2022-12-26T03:44, 'None', '']
Show total review count in main screen ['1730200873', 2023-10-14T13:00, 'None', '']
Special Fields ['1102281552', 2024-10-26T11:51, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T06:24, 'None', '']
Spell Checker with Custom Dictionaries ['390813456', 2023-10-20T12:00, 'None', mod]
SwiftAnki Quick Anki Navigation with Keyboard Shortcuts ['1467361433', 2024-09-13T17:38, 'None', '']
Symbols As You Type updated for 2310 ['1957191470', 2023-12-16T10:27, 'None', '']
Symbols ['1461102936', 2024-02-10T11:53, 'None', '']
The KING of Button Add-ons ['374005964', 2024-09-23T08:14, 'None', '']
The KING of Study Timers ['907028815', 2022-04-20T14:14, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T14:28, 'None', '']
Weekends and Holidays ['1992008104', 2022-12-19T20:24, 'None', '']
Wrapper meta-addon ['396502676', 2024-06-10T06:00, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T12:22, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T10:12, 'None', mod]
uworld_qid_to_anki_search ['607963104', 2024-10-15T15:53, 'None', mod]

===IDs of active AnkiWeb add-ons===
1008566916 1046608507 1052724801 1102281552 1135507717 1143247763 1143540799 1152543397 1172858842 1210908941 1322529746 1362209126 1374772155 1387847178 1435775540 1442112168 1461102936 1467361433 1536291224 1556734708 1625103157 1722658993 1730200873 1739176371 1771074083 1810938259 1898445115 1898790263 1908235722 1918380616 1949865265 1957191470 1992008104 2014569756 225180905 231569866 236593452 24411424 2491935955 272311064 291119185 304770511 307397307 318752047 374005964 385888438 390813456 396502676 46611790 511710206 561945101 594329229 607963104 633922407 635082046 649714433 663438166 688199788 734297936 738807903 744725736 759844606 805891399 817108664 864545277 874215009 907028815 911568091 947935257 952691989 960563361

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T03:22, 'None', mod]
Straight Reward ['957961234', 2023-11-01T10:11, 'None', '']

**Comment by AnKingMed** [comment]
is this still an issue?

**Comment by DoctorToBeIn23** [comment]
Haven't been able to reproduce.
