### ISSUE TITLE
Cannot save any style

### ISSUE THREAD

**Issue by m1e2d3** [ankipalace/Advanced-Card-Styles#8]
#### Problem description

Cannot save any style.it shows error
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 8
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-20 20:17:51

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1625103157\Buttons.py", line 107, in saveProfile
    nametxt.text(), cssTextWithConfigs, self.front, self.back)
  File "C:\Users\Username\AppData\Roaming\Anki2\addons21\1625103157\Buttons.py", line 233, in front
    return self.clayout.templates[self.clayout.ord]['qfmt']
IndexError: list index out of range

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 8
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-03-20 20:17:51
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2021-11-21T21:34, 'None', '']
    Add Table ['1237621971', 2021-12-06T01:57, 'None', mod]
    Additional Card Fields Fork for 21 ['744725736', 2022-02-22T03:52, 'None', '']
    Adjust Sound Volume ['2123044452', 2021-05-05T16:54, 'None', '']
    Advanced Browser ['874215009', 2022-01-31T04:37, 'None', '']
    Advanced Card Styles ['1625103157', 2021-09-23T17:21, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-04T00:16, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2022-02-13T13:27, 'None', mod]
    Anki Simulator ['817108664', 2021-08-08T00:54, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T05:50, 'v1.1.3', '']
    AnkiConnect ['2055492159', 2022-02-20T00:41, 'None', mod]
    AnkiWebView Inspector ['31746032', 2019-05-03T04:13, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2022-02-20T08:53, 'None', '']
    Basic Printing Support ['1025789669', 2022-03-04T16:44, 'None', '']
    Batch Download Pictures From Google Images ['561924305', 2020-07-09T18:21, 'None', '']
    Batch Editing ['291119185', 2019-06-03T00:17, 'None', '']
    BetterSearch ['1052724801', 2021-11-22T00:12, 'None', '']
    Browser Resizer ['1435775540', 2021-08-02T02:41, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-26T03:41, 'None', '']
    Button Colours Good Again ['2494384865', 2021-04-06T20:27, 'None', '']
    Clickable Tags v20 original ['380714095', 2022-01-31T04:28, 'None', '']
    Collapsible Fields ['1896168623', 2021-08-29T03:15, 'None', '']
    Colorful Browser Sidebar ['929609616', 2021-09-09T23:33, 'None', mod]
    Colorful toolbars ['388296573', 2019-11-19T17:15, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-24T03:33, 'None', '']
    Copy notes ['1566928056', 2021-12-25T01:26, 'None', '']
    Countdown To Events and Exams ['1143540799', 2021-03-14T02:10, 'None', '']
    Custom Styles font color background colour classes ['1899278645', 2021-03-03T06:11, 'None', '']
    Enhanced Cloze for Anki 21 ['1990296174', 2022-03-18T22:23, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-02-05T02:32, 'None', '']
    Field History ['1247884413', 2019-01-09T00:04, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T09:42, 'None', '']
    Hierarchical Tags 2 ['594329229', 2021-03-07T07:55, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T22:36, 'None', '']
    Image Editor ['307397307', 2021-12-19T17:28, 'None', mod]
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T07:51, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T12:31, 'None', mod]
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2021-07-25T03:47, 'None', '']
    Life Drain ['715575551', 2022-02-13T18:45, 'None', '']
    Markdown and KaTeX Support ['1087328706', 2022-02-10T22:14, 'None', '']
    Media Import ['1531997860', 2018-07-14T18:02, 'None', '']
    Merge Notes ['1425504015', 2022-01-21T17:18, 'None', '']
    Mindmap from tag hierarchy ['965278890', 2022-02-03T01:49, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T23:15, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T14:39, 'None', '']
    More Overview Stats 21 ['738807903', 2021-07-31T00:43, 'None', '']
    Multiple type fields on card for 21 ['711285688', 2020-06-13T15:48, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T23:02, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T11:56, 'None', '']
    Search and Replace Tags ['138501288', 2017-08-30T00:28, 'None', '']
    See Previous Card Ratings in Reviewer ['1906641654', 2021-08-20T03:02, 'None', '']
    Set Font Size ['651521808', 2018-09-30T16:53, 'None', mod]
    Simple Timer and Stopwatch for Anki 21 ['1423272642', 2018-01-25T04:33, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T14:41, 'None', '']
    Stats Plus ['1009670238', 2021-03-04T17:53, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-22T07:47, 'None', '']
    Symbols ['1461102936', 2019-04-19T01:51, 'None', mod]
    True Retention ['613684242', 2017-11-20T02:13, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-01-18T03:03, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2021-12-06T01:58, 'None', '']
    extended editor for field for tables searchreplace ['805891399', 2022-03-13T16:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1009670238 1025789669 1046608507 1052724801 1087328706 1136455830 1143540799 1172858842 1237621971 1247884413 1374772155 138501288 1423272642 1425504015 1435775540 1436550454 1461102936 1531997860 153625306 1556734708 1566928056 1593969147 1625103157 1896168623 1898445115 1899278645 1906641654 1990296174 2040501954 2055492159 2084557901 2123044452 225180905 2494384865 266436365 291119185 295889520 307397307 31746032 318752047 380714095 388296573 46611790 516643804 538879081 561924305 561945101 594329229 613684242 651521808 711285688 715575551 738807903 744725736 805891399 817108664 831846358 864545277 874215009 929609616 965278890
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Editor Live Preview ['1960039667', 2021-10-09T09:36, 'None', '']
    Enhance main window ['877182321', 2020-12-23T10:12, 'None', mod]
    Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2021-11-30T11:15, 'None', '']
    TagSelectorV2 ['1022577188', 2021-08-07T16:58, 'None', '']

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:Windows
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by AnKingMed** [comment]
sorry for the delay on this - never got notified. This should be working. If not let us know
