### ISSUE TITLE
Error when clicking advanced editor on a pixorize card

### ISSUE THREAD

**Issue by Zeroman123456** [ankipalace/Advanced-Card-Styles#9]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I  get this error when I try to use advanced editor on a card from pixorize deck.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-05-08 17:28:41

Caught exception:
Traceback (most recent call last):
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\Buttons.py", line 249, in advancedEditorButtonAction
    AdvancedStylerGui.ASGUI(self.clayout)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py", line 31, in __init__
    self.loadUI()
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py", line 41, in loadUI
    self.loadSettingsFromCss(text)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\AdvancedStylerGui.py", line 107, in loadSettingsFromCss
    self.profile.initializeFromCssString(filePath, "Custom")
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\CssProfile.py", line 47, in initializeFromCssString
    self.rootList = createRootListFromCssString(cssString)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\myCssParser.py", line 13, in createRootListFromCssString
    return createRootListFromItemsInFile(itemsInFile)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\myCssParser.py", line 23, in createRootListFromItemsInFile
    newDict = convertRuleContentToOrderedDict(rule.content)
  File "C:\Users\makka\AppData\Roaming\Anki2\addons21\1625103157\myCssParser.py", line 58, in convertRuleContentToOrderedDict
    showInfo(f'Some kind of error in CSS code on line {dec.source_line} (Last correct item was : ' +
TypeError: can only concatenate str (not "NoneType") to str

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by AnKingMed** [comment]
sorry for the delay - it's been a while. What kind of card was this? It may not work if it was a more fancy designed card
